package com.example.training.entity;

// Generated Jan 12, 2014 5:48:58 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Airport generated by hbm2java
 */
@Entity
@Table(name = "AIRPORT", schema = "PUBLIC", catalog = "TEST")
public class Airport implements java.io.Serializable {

	private int apId;
	private Country country;
	private String apName;

	public Airport() {
	}

	public Airport(int apId, Country country) {
		this.apId = apId;
		this.country = country;
	}

	public Airport(int apId, Country country, String apName) {
		this.apId = apId;
		this.country = country;
		this.apName = apName;
	}

	@Id
	@Column(name = "AP_ID", unique = true, nullable = false)
	public int getApId() {
		return this.apId;
	}

	public void setApId(int apId) {
		this.apId = apId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CN_ID", nullable = false)
	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	@Column(name = "AP_NAME", length = 40)
	public String getApName() {
		return this.apName;
	}

	public void setApName(String apName) {
		this.apName = apName;
	}

}
