package com.example.training.entity;

// Generated Jan 12, 2014 5:48:58 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmployeeSpeaksLanguage generated by hbm2java
 */
@Entity
@Table(name = "EMPLOYEE_SPEAKS_LANGUAGE", schema = "PUBLIC", catalog = "TEST")
public class EmployeeSpeaksLanguage implements java.io.Serializable {

	private EmployeeSpeaksLanguageId id;
	private SpokenLanguage spokenLanguage;
	private Employee employee;

	public EmployeeSpeaksLanguage() {
	}

	public EmployeeSpeaksLanguage(EmployeeSpeaksLanguageId id, SpokenLanguage spokenLanguage, Employee employee) {
		this.id = id;
		this.spokenLanguage = spokenLanguage;
		this.employee = employee;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "empId", column = @Column(name = "EMP_ID", nullable = false)),
			@AttributeOverride(name = "lanId", column = @Column(name = "LAN_ID", nullable = false)) })
	public EmployeeSpeaksLanguageId getId() {
		return this.id;
	}

	public void setId(EmployeeSpeaksLanguageId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LAN_ID", nullable = false, insertable = false, updatable = false)
	public SpokenLanguage getSpokenLanguage() {
		return this.spokenLanguage;
	}

	public void setSpokenLanguage(SpokenLanguage spokenLanguage) {
		this.spokenLanguage = spokenLanguage;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMP_ID", nullable = false, insertable = false, updatable = false)
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

}
