package com.example.training.entity;

// Generated Jan 12, 2014 5:48:58 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name = "EMPLOYEE", schema = "PUBLIC", catalog = "TEST")
public class Employee implements java.io.Serializable {

	private int empId;
	private Country country;
	private String empSurname;
	private String empFirstname;
	private Set<EmployeeSpeaksLanguage> employeeSpeaksLanguages = new HashSet<EmployeeSpeaksLanguage>(0);

	public Employee() {
	}

	public Employee(int empId, Country country) {
		this.empId = empId;
		this.country = country;
	}

	public Employee(int empId, Country country, String empSurname, String empFirstname, Set<EmployeeSpeaksLanguage> employeeSpeaksLanguages) {
		this.empId = empId;
		this.country = country;
		this.empSurname = empSurname;
		this.empFirstname = empFirstname;
		this.employeeSpeaksLanguages = employeeSpeaksLanguages;
	}

	@Id
	@Column(name = "EMP_ID", unique = true, nullable = false)
	public int getEmpId() {
		return this.empId;
	}

	public void setEmpId(int empId) {
		this.empId = empId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CN_ID", nullable = false)
	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	@Column(name = "EMP_SURNAME", length = 40)
	public String getEmpSurname() {
		return this.empSurname;
	}

	public void setEmpSurname(String empSurname) {
		this.empSurname = empSurname;
	}

	@Column(name = "EMP_FIRSTNAME", length = 40)
	public String getEmpFirstname() {
		return this.empFirstname;
	}

	public void setEmpFirstname(String empFirstname) {
		this.empFirstname = empFirstname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employee")
	public Set<EmployeeSpeaksLanguage> getEmployeeSpeaksLanguages() {
		return this.employeeSpeaksLanguages;
	}

	public void setEmployeeSpeaksLanguages(Set<EmployeeSpeaksLanguage> employeeSpeaksLanguages) {
		this.employeeSpeaksLanguages = employeeSpeaksLanguages;
	}

}
