package com.example.training.entity;

// Generated Jan 12, 2014 5:48:58 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SpokenLanguage generated by hbm2java
 */
@Entity
@Table(name = "SPOKEN_LANGUAGE", schema = "PUBLIC", catalog = "TEST")
public class SpokenLanguage implements java.io.Serializable {

	private int lanId;
	private String lanCode;
	private String lanName;
	private Set<EmployeeSpeaksLanguage> employeeSpeaksLanguages = new HashSet<EmployeeSpeaksLanguage>(0);

	public SpokenLanguage() {
	}

	public SpokenLanguage(int lanId) {
		this.lanId = lanId;
	}

	public SpokenLanguage(int lanId, String lanCode, String lanName, Set<EmployeeSpeaksLanguage> employeeSpeaksLanguages) {
		this.lanId = lanId;
		this.lanCode = lanCode;
		this.lanName = lanName;
		this.employeeSpeaksLanguages = employeeSpeaksLanguages;
	}

	@Id
	@Column(name = "LAN_ID", unique = true, nullable = false)
	public int getLanId() {
		return this.lanId;
	}

	public void setLanId(int lanId) {
		this.lanId = lanId;
	}

	@Column(name = "LAN_CODE", length = 2)
	public String getLanCode() {
		return this.lanCode;
	}

	public void setLanCode(String lanCode) {
		this.lanCode = lanCode;
	}

	@Column(name = "LAN_NAME", length = 40)
	public String getLanName() {
		return this.lanName;
	}

	public void setLanName(String lanName) {
		this.lanName = lanName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "spokenLanguage")
	public Set<EmployeeSpeaksLanguage> getEmployeeSpeaksLanguages() {
		return this.employeeSpeaksLanguages;
	}

	public void setEmployeeSpeaksLanguages(Set<EmployeeSpeaksLanguage> employeeSpeaksLanguages) {
		this.employeeSpeaksLanguages = employeeSpeaksLanguages;
	}

}
